name: flutter_hrlweibo
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
    #https://github.com/ZaraclaJ/audio_recorder
  path_provider: ^1.1.0
  file: ^5.0.4

  cupertino_icons: ^0.1.3

  #https://github.com/luanpotter/audioplayers
  audioplayers: ^0.15.1
  #https://github: com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
   #https://github.com/best-flutter/flutter_page_indicator
  flutter_page_indicator: ^0.0.3
  #https://github.com/flutter/plugins/tree/master/packages/video_player
  video_player:
  # https://github:com/brianegan/chewie:
  chewie: ^0.9.5
  #https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  #https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.9
  # https://github:com/fluttercandies/extended_text_field:
  extended_text_field: ^4.0.0
  url_launcher: 5.3.0
  # https://github: com/fluttercandies/extended_nested_scroll_view:
  extended_nested_scroll_view: ^0.4.0
  flutter_screenutil: ^0.5.2
  dio: 3.0.9
  fluttertoast: ^3.1.0
  shared_preferences: ^0.5.3
  synchronized: ^2.1.0
  event_bus: ^1.0.1
  # https://github.com/theyakka/fluro
  fluro: ^1.5.1
  #https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.6.1+4
  #https://github.com/adee42/flutter_keyboard_visibility
  # keyboard_visibility: ^0.5.6
  #https://github.com/adee42/flutter_keyboard_visibility/issues/42
  flutter_keyboard_visibility: ^3.2.2


   #https://github.com/Baseflow/flutter-permission-handler
  permission_handler:   '^3.0.0'


  #https://github.com/Daegalus/dart-uuid
  uuid: 2.0.4


  #https://pub.flutter-io.cn/packages/audio_recorder
  flutter_record_plugin:
        git:
          url: https://github.com/huangruiLearn/flutter_record_plugin.git
          ref: ca5a0f3821616d38842dde4a6588a1ce9ad5673d

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: HotSearch
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
