# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Runs all the tests"
  lane :forPgyer do
    build_app(export_method: "ad-hoc")
    pgyer(api_key: "4198f2f3876788e3a4dc1c73ef0cbc5c", user_key: "8e5911e4f450b2c4924454f4af3f438c", ipa:"../ios/Runner.ipa")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :adHoc do
    #gradle(task: "clean assembleRelease")
    #crashlytics
    build_app(export_method: "ad-hoc")
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
